# Generated by Django 3.1.4 on 2021-03-15 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dishes',
        ),
    ]
